export const QUIZ_CATEGORIES = [
  {
    id: "company_type",
    question: "Vilken bolagsform har du?",
    options: [
      { label: "Enskild firma", value: "enskild_firma" },
      { label: "Handelsbolag (HB)", value: "handelsbolag" },
      { label: "Kommanditbolag (KB)", value: "kommanditbolag" },
      { label: "Aktiebolag (AB)", value: "aktiebolag" },
      { label: "Ekonomisk förening", value: "ekonomisk_forening" },
      { label: "Ideell förening", value: "ideell_forening" },
      { label: "Planerar att starta", value: "planning" },
    ],
    multi: false,
  },
  {
    id: "company_age",
    question: "När startades företaget?",
    description: "Vissa bidrag har krav på hur nytt eller gammalt företaget är",
    options: [
      { label: "Har inte startat än", value: "not_started" },
      { label: "Mindre än 1 år sedan", value: "less_1y" },
      { label: "1–3 år sedan", value: "1_3y" },
      { label: "3–5 år sedan", value: "3_5y" },
      { label: "Mer än 5 år sedan", value: "over_5y" },
    ],
    multi: false,
  },
  {
    id: "employees",
    question: "Hur många anställda har företaget?",
    options: [
      { label: "0 — bara jag (solo)", value: "solo" },
      { label: "1–9 (mikroföretag)", value: "micro" },
      { label: "10–49 (litet företag)", value: "small" },
      { label: "50–249 (medelstort)", value: "medium" },
      { label: "250+ (stort företag)", value: "large" },
    ],
    multi: false,
  },
  {
    id: "region",
    question: "Vilket län är företaget baserat i?",
    description: "Regionala bidrag varierar kraftigt mellan länen",
    options: [
      { label: "Stockholm", value: "stockholm" },
      { label: "Västra Götaland", value: "vastra_gotaland" },
      { label: "Skåne", value: "skane" },
      { label: "Östergötland", value: "ostergotland" },
      { label: "Uppsala", value: "uppsala" },
      { label: "Jönköping", value: "jonkoping" },
      { label: "Halland", value: "halland" },
      { label: "Örebro", value: "orebro" },
      { label: "Södermanland", value: "sodermanland" },
      { label: "Dalarna", value: "dalarna" },
      { label: "Gävleborg", value: "gavleborg" },
      { label: "Värmland", value: "varmland" },
      { label: "Västmanland", value: "vastmanland" },
      { label: "Norrbotten", value: "norrbotten" },
      { label: "Västerbotten", value: "vasterbotten" },
      { label: "Västernorrland", value: "vasternorrland" },
      { label: "Jämtland", value: "jamtland" },
      { label: "Kalmar", value: "kalmar" },
      { label: "Kronoberg", value: "kronoberg" },
      { label: "Blekinge", value: "blekinge" },
      { label: "Gotland", value: "gotland" },
    ],
    multi: false,
  },
  {
    id: "needs",
    question: "Vad behöver ditt företag hjälp med? (Välj alla som stämmer)",
    options: [
      { label: "Investering i verksamheten", value: "investment" },
      { label: "Produktutveckling", value: "product_dev" },
      { label: "Export / Internationalisering", value: "export" },
      { label: "Digitalisering", value: "digitalization" },
      { label: "Hållbarhet / Klimatomställning", value: "sustainability" },
      { label: "Anställa personal / Kompetensutveckling", value: "hiring_skills" },
      { label: "Marknadsföring / Försäljning", value: "marketing_sales" },
      { label: "Starta eget-stöd", value: "startup_support" },
      { label: "Forskning & Innovation", value: "rnd" },
      { label: "Lokaler / Expansion / Flytt", value: "premises" },
      { label: "Patent / Immaterialrätt", value: "ip_patents" },
      { label: "Ekonomi / Likviditet", value: "finance_liquidity" },
      { label: "Omställning / Ny inriktning", value: "pivot" },
      { label: "Vet inte riktigt än", value: "unsure" },
    ],
    multi: true,
  },
  {
    id: "revenue",
    question: "Vad är företagets ungefärliga årsomsättning?",
    options: [
      { label: "Ingen omsättning än", value: "zero" },
      { label: "Under 300 000 kr", value: "under_300k" },
      { label: "300 000 – 600 000 kr", value: "300k_600k" },
      { label: "600 000 – 3 mkr", value: "600k_3m" },
      { label: "3 – 10 mkr", value: "3m_10m" },
      { label: "10 – 50 mkr", value: "10m_50m" },
      { label: "Över 50 mkr", value: "over_50m" },
      { label: "Vill inte säga", value: "prefer_not_to_say" },
    ],
    multi: false,
  },
  {
    id: "industry",
    question: "Vilken bransch ligger närmast? (Välj alla som stämmer)",
    description: "Välj en eller flera — många bidrag täcker flera branscher",
    options: [
      { label: "Tech / IT / SaaS", value: "tech" },
      { label: "Handel / E-commerce", value: "ecommerce" },
      { label: "Tillverkning / Industri", value: "manufacturing" },
      { label: "Bygg / Fastighet", value: "construction" },
      { label: "Städ / Fastighetsservice", value: "cleaning_facility" },
      { label: "Restaurang / Besöksnäring", value: "hospitality" },
      { label: "Hälsa / Vård / Life Science", value: "health" },
      { label: "Skönhet / Frisör / Personlig vård", value: "beauty_personal" },
      { label: "Transport / Logistik", value: "transport" },
      { label: "Fordon / Verkstad", value: "automotive" },
      { label: "Konsult / Tjänsteföretag", value: "consulting" },
      { label: "Kreativa branschen / Kultur", value: "creative" },
      { label: "Jordbruk / Livsmedel", value: "agriculture" },
      { label: "Energi / Cleantech", value: "energy" },
      { label: "Utbildning", value: "education" },
      { label: "Annat / Blandat", value: "other" },
    ],
    multi: true,
  },
  {
    id: "offering_type",
    question: "Vad erbjuder företaget?",
    description: "Påverkar vilka typer av bidrag ni kan söka",
    options: [
      { label: "Fysiska produkter / Varor", value: "physical_products" },
      { label: "Tjänster", value: "services" },
      { label: "Både varor och tjänster", value: "both" },
      { label: "Vet inte riktigt än", value: "unsure" },
    ],
    multi: false,
  },
];
