export const QUIZ_CATEGORIES = [
  {
    id: "company_type",
    question: "Vilken bolagsform har du?",
    options: [
      { label: "Enskild firma", icon: "👤", value: "enskild_firma" },
      { label: "Handelsbolag (HB)", icon: "🤝", value: "handelsbolag" },
      { label: "Kommanditbolag (KB)", icon: "📑", value: "kommanditbolag" },
      { label: "Aktiebolag (AB)", icon: "🏢", value: "aktiebolag" },
      { label: "Ekonomisk förening", icon: "🤲", value: "ekonomisk_forening" },
      { label: "Ideell förening", icon: "💛", value: "ideell_forening" },
      { label: "Planerar att starta", icon: "💡", value: "planning" },
    ],
    multi: false,
  },
  {
    id: "employees",
    question: "Hur många anställda har företaget?",
    options: [
      { label: "0 — bara jag (solo)", icon: "👤", value: "solo" },
      { label: "1–9 (mikroföretag)", icon: "👥", value: "micro" },
      { label: "10–49 (litet företag)", icon: "🏬", value: "small" },
      { label: "50–249 (medelstort)", icon: "🏢", value: "medium" },
      { label: "250+ (stort företag)", icon: "🏛️", value: "large" },
    ],
    multi: false,
  },
  {
    id: "region",
    question: "Vilket län är företaget baserat i?",
    description: "Regionala bidrag varierar kraftigt mellan länen",
    options: [
      { label: "Stockholm", value: "stockholm" },
      { label: "Västra Götaland", value: "vastra_gotaland" },
      { label: "Skåne", value: "skane" },
      { label: "Östergötland", value: "ostergotland" },
      { label: "Uppsala", value: "uppsala" },
      { label: "Jönköping", value: "jonkoping" },
      { label: "Halland", value: "halland" },
      { label: "Örebro", value: "orebro" },
      { label: "Södermanland", value: "sodermanland" },
      { label: "Dalarna", value: "dalarna" },
      { label: "Gävleborg", value: "gavleborg" },
      { label: "Värmland", value: "varmland" },
      { label: "Västmanland", value: "vastmanland" },
      { label: "Norrbotten", value: "norrbotten" },
      { label: "Västerbotten", value: "vasterbotten" },
      { label: "Västernorrland", value: "vasternorrland" },
      { label: "Jämtland", value: "jamtland" },
      { label: "Kalmar", value: "kalmar" },
      { label: "Kronoberg", value: "kronoberg" },
      { label: "Blekinge", value: "blekinge" },
      { label: "Gotland", value: "gotland" },
    ],
    multi: false,
  },
  {
    id: "needs",
    question: "Vad behöver ditt företag hjälp med? (Välj alla som stämmer)",
    options: [
      { label: "Investering i verksamheten", icon: "💰", value: "investment" },
      { label: "Produktutveckling", icon: "🔧", value: "product_dev" },
      { label: "Export / Internationalisering", icon: "🌍", value: "export" },
      { label: "Digitalisering", icon: "💻", value: "digitalization" },
      { label: "Hållbarhet / Klimatomställning", icon: "🌿", value: "sustainability" },
      { label: "Anställa personal / Kompetensutveckling", icon: "👥", value: "hiring_skills" },
      { label: "Starta eget-stöd", icon: "🚀", value: "startup_support" },
      { label: "Forskning & Innovation", icon: "🔬", value: "rnd" },
    ],
    multi: true,
  },
  {
    id: "revenue",
    question: "Vad är företagets ungefärliga årsomsättning?",
    options: [
      { label: "Ingen omsättning än", value: "zero" },
      { label: "Under 500 000 kr", value: "under_500k" },
      { label: "500 000 – 3 mkr", value: "500k_3m" },
      { label: "3 – 10 mkr", value: "3m_10m" },
      { label: "10 – 50 mkr", value: "10m_50m" },
      { label: "Över 50 mkr", value: "over_50m" },
    ],
    multi: false,
  },
  {
    id: "industry",
    question: "Vilken bransch ligger närmast?",
    description: "Välj det som stämmer bäst — många bidrag täcker flera branscher",
    options: [
      { label: "Tech / IT / SaaS", icon: "🤖", value: "tech" },
      { label: "Handel / E-commerce", icon: "🛒", value: "ecommerce" },
      { label: "Tillverkning / Industri", icon: "🏭", value: "manufacturing" },
      { label: "Bygg / Fastighet", icon: "🏗️", value: "construction" },
      { label: "Restaurang / Besöksnäring", icon: "🍽️", value: "hospitality" },
      { label: "Hälsa / Vård / Life Science", icon: "🏥", value: "health" },
      { label: "Transport / Logistik", icon: "🚛", value: "transport" },
      { label: "Konsult / Tjänsteföretag", icon: "💼", value: "consulting" },
      { label: "Kreativa branschen / Kultur", icon: "🎨", value: "creative" },
      { label: "Jordbruk / Livsmedel", icon: "🌾", value: "agriculture" },
      { label: "Energi / Cleantech", icon: "⚡", value: "energy" },
      { label: "Utbildning", icon: "📚", value: "education" },
      { label: "Annat / Blandat", icon: "✨", value: "other" },
    ],
    multi: false,
  },
];
