export const QUIZ_CATEGORIES = [
  {
    id: "company_type",
    question: "Vilken bolagsform har du?",
    options: [
      { label: "Enskild firma", value: "enskild_firma" },
      { label: "Handelsbolag (HB)", value: "handelsbolag" },
      { label: "Kommanditbolag (KB)", value: "kommanditbolag" },
      { label: "Aktiebolag (AB)", value: "aktiebolag" },
      { label: "Ekonomisk förening", value: "ekonomisk_forening" },
      { label: "Ideell förening", value: "ideell_forening" },
      { label: "Planerar att starta", value: "planning" },
    ],
    multi: false,
  },
  {
    id: "employees",
    question: "Hur många anställda har företaget?",
    options: [
      { label: "0 — bara jag (solo)", value: "solo" },
      { label: "1–9 (mikroföretag)", value: "micro" },
      { label: "10–49 (litet företag)", value: "small" },
      { label: "50–249 (medelstort)", value: "medium" },
      { label: "250+ (stort företag)", value: "large" },
    ],
    multi: false,
  },
  {
    id: "region",
    question: "Vilket län är företaget baserat i?",
    description: "Regionala bidrag varierar kraftigt mellan länen",
    options: [
      { label: "Stockholm", value: "stockholm" },
      { label: "Västra Götaland", value: "vastra_gotaland" },
      { label: "Skåne", value: "skane" },
      { label: "Östergötland", value: "ostergotland" },
      { label: "Uppsala", value: "uppsala" },
      { label: "Jönköping", value: "jonkoping" },
      { label: "Halland", value: "halland" },
      { label: "Örebro", value: "orebro" },
      { label: "Södermanland", value: "sodermanland" },
      { label: "Dalarna", value: "dalarna" },
      { label: "Gävleborg", value: "gavleborg" },
      { label: "Värmland", value: "varmland" },
      { label: "Västmanland", value: "vastmanland" },
      { label: "Norrbotten", value: "norrbotten" },
      { label: "Västerbotten", value: "vasterbotten" },
      { label: "Västernorrland", value: "vasternorrland" },
      { label: "Jämtland", value: "jamtland" },
      { label: "Kalmar", value: "kalmar" },
      { label: "Kronoberg", value: "kronoberg" },
      { label: "Blekinge", value: "blekinge" },
      { label: "Gotland", value: "gotland" },
    ],
    multi: false,
  },
  {
    id: "needs",
    question: "Vad behöver ditt företag hjälp med? (Välj alla som stämmer)",
    options: [
      { label: "Investering i verksamheten", value: "investment" },
      { label: "Produktutveckling", value: "product_dev" },
      { label: "Export / Internationalisering", value: "export" },
      { label: "Digitalisering", value: "digitalization" },
      { label: "Hållbarhet / Klimatomställning", value: "sustainability" },
      { label: "Anställa personal / Kompetensutveckling", value: "hiring_skills" },
      { label: "Marknadsföring / Försäljning", value: "marketing_sales" },
      { label: "Starta eget-stöd", value: "startup_support" },
      { label: "Forskning & Innovation", value: "rnd" },
      { label: "Vet inte riktigt än", value: "unsure" },
    ],
    multi: true,
  },
  {
    id: "revenue",
    question: "Vad är företagets ungefärliga årsomsättning?",
    options: [
      { label: "Ingen omsättning än", value: "zero" },
      { label: "Under 500 000 kr", value: "under_500k" },
      { label: "500 000 – 3 mkr", value: "500k_3m" },
      { label: "3 – 10 mkr", value: "3m_10m" },
      { label: "10 – 50 mkr", value: "10m_50m" },
      { label: "Över 50 mkr", value: "over_50m" },
    ],
    multi: false,
  },
  {
    id: "industry",
    question: "Vilken bransch ligger närmast?",
    description: "Välj det som stämmer bäst — många bidrag täcker flera branscher",
    options: [
      { label: "Tech / IT / SaaS", value: "tech" },
      { label: "Handel / E-commerce", value: "ecommerce" },
      { label: "Tillverkning / Industri", value: "manufacturing" },
      { label: "Bygg / Fastighet", value: "construction" },
      { label: "Restaurang / Besöksnäring", value: "hospitality" },
      { label: "Hälsa / Vård / Life Science", value: "health" },
      { label: "Transport / Logistik", value: "transport" },
      { label: "Konsult / Tjänsteföretag", value: "consulting" },
      { label: "Kreativa branschen / Kultur", value: "creative" },
      { label: "Jordbruk / Livsmedel", value: "agriculture" },
      { label: "Energi / Cleantech", value: "energy" },
      { label: "Utbildning", value: "education" },
      { label: "Annat / Blandat", value: "other" },
    ],
    multi: false,
  },
];
